// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teachers.sql

package db

import (
	"context"
)

const createTeacher = `-- name: CreateTeacher :one
INSERT INTO teachers (
  name
) VALUES (
  $1
) RETURNING id, name, created_at
`

func (q *Queries) CreateTeacher(ctx context.Context, name string) (Teacher, error) {
	row := q.db.QueryRow(ctx, createTeacher, name)
	var i Teacher
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteTeacher = `-- name: DeleteTeacher :exec
DELETE FROM teachers
WHERE id = $1
`

func (q *Queries) DeleteTeacher(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTeacher, id)
	return err
}

const getTeacher = `-- name: GetTeacher :one
SELECT id, name, created_at FROM teachers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTeacher(ctx context.Context, id int32) (Teacher, error) {
	row := q.db.QueryRow(ctx, getTeacher, id)
	var i Teacher
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listTeachers = `-- name: ListTeachers :many
SELECT id, name, created_at FROM teachers
ORDER BY name
`

func (q *Queries) ListTeachers(ctx context.Context) ([]Teacher, error) {
	rows, err := q.db.Query(ctx, listTeachers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Teacher
	for rows.Next() {
		var i Teacher
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeacher = `-- name: UpdateTeacher :one
UPDATE teachers
  set name = $2
WHERE id = $1
RETURNING id, name, created_at
`

type UpdateTeacherParams struct {
	ID   int32
	Name string
}

func (q *Queries) UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, updateTeacher, arg.ID, arg.Name)
	var i Teacher
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
